### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [mkulinski/splutry#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by mkulinski** [comment]
I added the tag. Maybe you guys can optimize the the Firehose Project website for smaller browser windows :)
![screen shot 2015-12-24 at 9 16 52 am](https://cloud.githubusercontent.com/assets/8060507/11996997/6502e1a0-aa25-11e5-999c-b36fd6c9698b.png)

**Comment by kenmazaika** [comment]
Your app looks awesome!  Thumbs up.  Thanks for letting us know about the overlap of your name and the resources tab.  We're making changes to the navigation bar in the upcoming weeks, so that should resolve the problem.
